<?php
namespace KaarBooking\Component\KaarBooking\Administrator\View\Inspections;defined('_JEXEC') or die;use Joomla\CMS\Factory;use Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;
final class HtmlView extends BaseHtmlView
{
 public array $vehicles=[],$drivers=[],$companies=[],$types=[],$items=[],$filters=[];
 public function display($tpl=null):void
 {
  if(!Factory::getApplication()->getIdentity()->authorise('kaarbooking.vehicle.inspect','com_kaarbooking')&&!Factory::getApplication()->getIdentity()->authorise('core.manage','com_kaarbooking'))throw new \RuntimeException('Not authorised',403);$app=Factory::getApplication();$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$this->filters=['search'=>trim((string)$app->input->getString('filter_search','')),'driver'=>$app->input->getInt('filter_driver'),'company'=>$app->input->getInt('filter_company'),'type'=>$app->input->getInt('filter_type'),'result'=>$app->input->getCmd('filter_result','')];$this->vehicles=$db->setQuery('SELECT id,registration_number FROM #__kaar_vehicles WHERE state=1 ORDER BY registration_number')->loadAssocList()?:[];$this->drivers=$db->setQuery('SELECT id,display_name FROM #__kaar_drivers ORDER BY display_name')->loadAssocList()?:[];$this->companies=$db->setQuery('SELECT id,name FROM #__kaar_companies ORDER BY name')->loadAssocList()?:[];$this->types=$db->setQuery('SELECT id,title FROM #__kaar_vehicle_types ORDER BY ordering,title')->loadAssocList()?:[];$q=$db->getQuery(true)->select(['i.*','v.registration_number','v.make','v.model','d.display_name AS driver_name','u.name AS inspector_name','c.name AS company_name','t.title AS type_title'])->from('#__kaar_vehicle_inspections i')->join('INNER','#__kaar_vehicles v ON v.id=i.vehicle_id')->join('LEFT','#__kaar_drivers d ON d.id=i.driver_id')->join('LEFT','#__users u ON u.id=i.inspector_id')->join('LEFT','#__kaar_companies c ON c.id=v.company_id')->join('LEFT','#__kaar_vehicle_types t ON t.id=v.vehicle_type_id');if($this->filters['search']!=='')$q->where('(v.registration_number LIKE '.$db->quote('%'.$this->filters['search'].'%').' OR v.make LIKE '.$db->quote('%'.$this->filters['search'].'%').' OR v.model LIKE '.$db->quote('%'.$this->filters['search'].'%').' OR d.display_name LIKE '.$db->quote('%'.$this->filters['search'].'%').' OR c.name LIKE '.$db->quote('%'.$this->filters['search'].'%').')');if($this->filters['driver'])$q->where('i.driver_id='.(int)$this->filters['driver']);if($this->filters['company'])$q->where('v.company_id='.(int)$this->filters['company']);if($this->filters['type'])$q->where('v.vehicle_type_id='.(int)$this->filters['type']);if($this->filters['result']!=='')$q->where('i.result='.$db->quote($this->filters['result']));$q->order('i.inspection_date DESC');$this->items=$db->setQuery($q,0,500)->loadAssocList()?:[];parent::display($tpl);
 }
}
