<?php
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Router\Route;use Joomla\CMS\Session\Session;
$token=Session::getFormToken();
?>
<div class="container-fluid kaar-booking">
<h1>Compliance &amp; KYC</h1>
<div class="alert alert-info">Customer, driver and vehicle originals use an audited, no-store inline preview. No download action is exposed.</div>
<div class="card mb-4"><div class="card-body"><h2 class="h4">Add document type</h2><form action="<?php echo Route::_('index.php?option=com_kaarbooking&task=kyc.saveType'); ?>" method="post" class="row g-3"><div class="col-md-3"><input class="form-control" name="title" required maxlength="190" placeholder="Police verification"></div><div class="col-md-3"><input class="form-control" name="code" required pattern="[a-z][a-z0-9_]{1,63}" placeholder="police_verification"></div><div class="col-md-2"><select class="form-select" name="type_subject"><option value="customer">Customer</option><option value="driver">Driver</option><option value="vehicle">Vehicle</option></select></div><div class="col-md-2"><label><input type="checkbox" name="expiry_required" value="1"> Expiry required</label><br><label><input type="checkbox" name="required_for_compliance" value="1" checked> Mandatory</label></div><div class="col-md-2"><button class="btn btn-outline-primary">Add type</button></div><?php echo HTMLHelper::_('form.token'); ?></form></div></div>
<div class="card mb-4"><div class="card-body"><h2 class="h4">Submit document</h2>
<form action="<?php echo Route::_('index.php?option=com_kaarbooking&task=kyc.upload'); ?>" method="post" enctype="multipart/form-data" class="row g-3">
<div class="col-md-3"><label class="form-label" for="subject_type">Owner type</label><select class="form-select" id="subject_type" name="subject_type" required><option value="customer">Customer</option><option value="driver">Driver</option><option value="vehicle">Vehicle</option></select></div>
<div class="col-md-3"><label class="form-label" for="subject_id">Owner</label><select class="form-select" id="subject_id" name="subject_id" required><?php foreach($this->subjects as $type=>$rows)foreach($rows as $row): ?><option data-subject-type="<?php echo $type; ?>" value="<?php echo (int)$row['id']; ?>"><?php echo htmlspecialchars(ucfirst($type).' — '.$row['label'],ENT_QUOTES,'UTF-8'); ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label class="form-label" for="document_type">Document type</label><select class="form-select" id="document_type" name="document_type" required><?php foreach($this->documentTypes as $type): ?><option data-subject-type="<?php echo htmlspecialchars($type['subject_type'],ENT_QUOTES,'UTF-8'); ?>" value="<?php echo htmlspecialchars($type['code'],ENT_QUOTES,'UTF-8'); ?>"><?php echo htmlspecialchars($type['title'].' ('.$type['subject_type'].')',ENT_QUOTES,'UTF-8'); ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label class="form-label" for="expiry_date">Expiry date</label><input class="form-control" type="date" id="expiry_date" name="expiry_date"></div>
<div class="col-md-6"><label class="form-label" for="proof">PDF/image, maximum 5 MB</label><input class="form-control" type="file" id="proof" name="proof" accept="application/pdf,image/jpeg,image/png,image/webp" required></div>
<div class="col-md-3 align-self-end"><button class="btn btn-primary" type="submit">Submit for verification</button></div><?php echo HTMLHelper::_('form.token'); ?></form></div></div>
<div class="table-responsive"><table class="table table-striped"><thead><tr><th>Owner</th><th>Document</th><th>Expiry</th><th>Status</th><th>Submitted</th><th>Decision</th></tr></thead><tbody>
<?php foreach($this->items as $item): ?><tr><td><?php echo htmlspecialchars(ucfirst($item['subject_type']).' — '.$item['subject_label'],ENT_QUOTES,'UTF-8'); ?></td><td><?php echo htmlspecialchars($item['document_type'],ENT_QUOTES,'UTF-8'); ?><?php if(!empty($item['file_key'])): ?> <a target="_blank" rel="noopener" href="<?php echo Route::_('index.php?option=com_kaarbooking&task=kyc.preview&id='.(int)$item['id'].'&'.$token.'=1'); ?>">Preview</a><?php endif; ?></td><td><?php echo htmlspecialchars($item['expiry_date']??'—',ENT_QUOTES,'UTF-8'); ?></td><td><?php echo htmlspecialchars($item['status'],ENT_QUOTES,'UTF-8'); ?></td><td><?php echo htmlspecialchars($item['created'],ENT_QUOTES,'UTF-8'); ?></td><td><form action="<?php echo Route::_('index.php?option=com_kaarbooking&task=kyc.decide'); ?>" method="post" class="d-flex gap-2"><input type="hidden" name="id" value="<?php echo (int)$item['id']; ?>"><select name="decision" class="form-select form-select-sm"><option value="verified">Verify</option><option value="rejected">Reject</option><option value="resubmission_required">Request resubmission</option></select><input name="reason" required class="form-control form-control-sm" placeholder="Decision reason"><button class="btn btn-primary btn-sm">Save</button><?php echo HTMLHelper::_('form.token'); ?></form></td></tr><?php endforeach; ?>
<?php if(!$this->items): ?><tr><td colspan="6">No documents submitted.</td></tr><?php endif; ?></tbody></table></div></div>
