<?php
namespace KaarBooking\Component\KaarBooking\Administrator\View\Vehicles;defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;
final class HtmlView extends BaseHtmlView{public array $items=[],$types=[],$companies=[],$stats=[],$filters=[];public function display($tpl=null):void{if(!Factory::getApplication()->getIdentity()->authorise('core.manage','com_kaarbooking'))throw new \RuntimeException('Not authorised',403);$app=Factory::getApplication();$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$this->filters=['search'=>trim((string)$app->input->getString('filter_search','')),'type'=>$app->input->getInt('filter_type'),'company'=>$app->input->getInt('filter_company'),'compliance'=>$app->input->getCmd('filter_compliance')];$q=$db->getQuery(true)->select(['v.*','t.title AS type_title','c.name AS company_name','m.path AS image_path'])->from($db->quoteName('#__kaar_vehicles','v'))->join('LEFT',$db->quoteName('#__kaar_vehicle_types','t').' ON t.id=v.vehicle_type_id')->join('LEFT',$db->quoteName('#__kaar_companies','c').' ON c.id=v.company_id')->join('LEFT',$db->quoteName('#__kaar_media','m')." ON m.subject_type='vehicle' AND m.subject_id=v.id AND m.purpose='profile'");if($this->filters['search']!=='')$q->where('(v.registration_number LIKE '.$db->quote('%'.$this->filters['search'].'%').' OR v.make LIKE '.$db->quote('%'.$this->filters['search'].'%').' OR v.model LIKE '.$db->quote('%'.$this->filters['search'].'%').')');if($this->filters['type'])$q->where('v.vehicle_type_id='.(int)$this->filters['type']);if($this->filters['company'])$q->where('v.company_id='.(int)$this->filters['company']);if($this->filters['compliance']!=='')$q->where('v.compliance_status='.$db->quote($this->filters['compliance']));$q->order('v.registration_number');$this->items=$db->setQuery($q,0,500)->loadAssocList()?:[];$this->types=$db->setQuery($db->getQuery(true)->select(['id','title'])->from('#__kaar_vehicle_types')->where('state=1')->order('ordering,title'))->loadAssocList()?:[];$this->companies=$db->setQuery($db->getQuery(true)->select(['id','name'])->from('#__kaar_companies')->where('status='.$db->quote('active'))->order('name'))->loadAssocList()?:[];$this->stats=['total'=>(int)$db->setQuery('SELECT COUNT(*) FROM #__kaar_vehicles')->loadResult(),'active'=>(int)$db->setQuery("SELECT COUNT(*) FROM #__kaar_vehicles WHERE operational_status='active'")->loadResult(),'compliant'=>(int)$db->setQuery("SELECT COUNT(*) FROM #__kaar_vehicles WHERE compliance_status='verified'")->loadResult(),'blocked'=>(int)$db->setQuery("SELECT COUNT(*) FROM #__kaar_vehicles WHERE operational_status='blocked'")->loadResult()];parent::display($tpl);}}






