<?php
namespace KaarBooking\Component\KaarBooking\Api\Controller;
defined('_JEXEC') or die;
use Joomla\CMS\Component\ComponentHelper; use Joomla\CMS\Factory; use Joomla\CMS\User\UserHelper;
final class AuthController extends BaseJsonController
{
    private function body(): array { $data=json_decode(file_get_contents('php://input'),true,32,JSON_THROW_ON_ERROR);return is_array($data)?$data:[]; }
    public function challenge(): never
    {
        $body=$this->body();$email=strtolower(trim((string)($body['email']??'')));$generic=['accepted'=>true,'message'=>'If the address can receive a code, it will arrive shortly.'];if(!filter_var($email,FILTER_VALIDATE_EMAIL))$this->respond($generic,202);
        $db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$destinationHash=hash_hmac('sha256',$email,(string)$this->app->get('secret'));$since=gmdate('Y-m-d H:i:s',time()-600);$q=$db->getQuery(true)->select('COUNT(*)')->from($db->quoteName('#__kaar_otp_challenges'))->where($db->quoteName('destination_hash').'='.$db->quote($destinationHash))->where($db->quoteName('created').'>='.$db->quote($since));if((int)$db->setQuery($q)->loadResult()>=3)$this->respond($generic,202);
        $otpMinutes=max(3,min(20,(int)ComponentHelper::getParams('com_kaarbooking')->get('api_otp_minutes',10)));$otp=(string)random_int(100000,999999);$now=Factory::getDate();$row=(object)['subject_type'=>'email_login','subject_id'=>0,'purpose'=>'mobile_login','destination_hash'=>$destinationHash,'otp_hash'=>password_hash($otp,PASSWORD_DEFAULT),'expires_at'=>(clone $now)->modify('+'.$otpMinutes.' minutes')->toSql(),'attempts'=>0,'max_attempts'=>5,'consumed_at'=>null,'created'=>$now->toSql()];$db->insertObject('#__kaar_otp_challenges',$row,'id');
        try{$mailer=Factory::getContainer()->get(\Joomla\CMS\Mail\MailerFactoryInterface::class)->createMailer();$mailer->addRecipient($email)->setSubject('Your Kaar Booking verification code')->setBody('Your verification code is '.$otp.'. It expires in '.$otpMinutes.' minutes.')->Send();}catch(\Throwable $error){}
        $this->respond($generic,202);
    }
    public function verify(): never
    {
        $body=$this->body();$email=strtolower(trim((string)($body['email']??'')));$otp=trim((string)($body['otp']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL)||!preg_match('/^\d{6}$/',$otp))$this->respond(['code'=>'invalid_code','message'=>'The code is invalid or expired.'],401);
        $db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$hash=hash_hmac('sha256',$email,(string)$this->app->get('secret'));$now=Factory::getDate();$q=$db->getQuery(true)->select('*')->from($db->quoteName('#__kaar_otp_challenges'))->where($db->quoteName('destination_hash').'='.$db->quote($hash))->where($db->quoteName('purpose').'='.$db->quote('mobile_login'))->where($db->quoteName('consumed_at').' IS NULL')->where($db->quoteName('expires_at').'>='.$db->quote($now->toSql()))->order($db->quoteName('id').' DESC');$challenge=$db->setQuery($q,0,1)->loadObject();if(!$challenge||(int)$challenge->attempts>=(int)$challenge->max_attempts||!password_verify($otp,$challenge->otp_hash)){if($challenge){$db->setQuery($db->getQuery(true)->update($db->quoteName('#__kaar_otp_challenges'))->set($db->quoteName('attempts').'='.$db->quoteName('attempts').'+1')->where($db->quoteName('id').'='.(int)$challenge->id))->execute();}$this->respond(['code'=>'invalid_code','message'=>'The code is invalid or expired.'],401);}
        $db->transactionStart();try{$db->setQuery($db->getQuery(true)->update($db->quoteName('#__kaar_otp_challenges'))->set($db->quoteName('consumed_at').'='.$db->quote($now->toSql()))->where($db->quoteName('id').'='.(int)$challenge->id)->where($db->quoteName('consumed_at').' IS NULL'))->execute();if($db->getAffectedRows()!==1)throw new \RuntimeException('Code already used');$userId=(int)$db->setQuery($db->getQuery(true)->select('id')->from($db->quoteName('#__users'))->where($db->quoteName('email').'='.$db->quote($email)),0,1)->loadResult();if($userId<=0){$user=new \Joomla\CMS\User\User();$user->bind(['name'=>strstr($email,'@',true)?:'Kaar customer','username'=>$email,'email'=>$email,'password'=>UserHelper::genRandomPassword(32),'groups'=>[2]]);if(!$user->save())throw new \RuntimeException('Account creation failed');$userId=(int)$user->id;}$tokens=$this->issueSession($userId,(string)($body['deviceName']??'Mobile app'),null,$db);$db->transactionCommit();$this->respond(['data'=>$tokens],200);}catch(\Throwable $error){$db->transactionRollback();$this->respond(['code'=>'verification_failed','message'=>'Verification could not be completed.'],500);}
    }
    public function refresh(): never
    {
        $body=$this->body();$token=trim((string)($body['refreshToken']??''));if(!preg_match('/^kbr_[A-Za-z0-9_-]{50,}$/',$token))$this->respond(['code'=>'invalid_refresh','message'=>'Sign in again.'],401);$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$hash=hash('sha256',$token);$row=$db->setQuery($db->getQuery(true)->select('*')->from($db->quoteName('#__kaar_api_sessions'))->where($db->quoteName('refresh_hash').'='.$db->quote($hash)),0,1)->loadObject();$now=Factory::getDate();if(!$row)$this->respond(['code'=>'invalid_refresh','message'=>'Sign in again.'],401);if($row->revoked_at!==null){$db->setQuery($db->getQuery(true)->update($db->quoteName('#__kaar_api_sessions'))->set($db->quoteName('revoked_at').'='.$db->quote($now->toSql()))->set($db->quoteName('revoke_reason').'='.$db->quote('refresh_reuse'))->where($db->quoteName('family_id').'='.$db->quote($row->family_id))->where($db->quoteName('revoked_at').' IS NULL'))->execute();$this->respond(['code'=>'refresh_reuse','message'=>'Session revoked; sign in again.'],401);}if($row->refresh_expires<$now->toSql())$this->respond(['code'=>'refresh_expired','message'=>'Sign in again.'],401);
        $db->transactionStart();try{$db->setQuery($db->getQuery(true)->update($db->quoteName('#__kaar_api_sessions'))->set($db->quoteName('revoked_at').'='.$db->quote($now->toSql()))->set($db->quoteName('revoke_reason').'='.$db->quote('rotated'))->where($db->quoteName('id').'='.(int)$row->id)->where($db->quoteName('revoked_at').' IS NULL'))->execute();if($db->getAffectedRows()!==1)throw new \RuntimeException('Already rotated');$tokens=$this->issueSession((int)$row->user_id,(string)($body['deviceName']??$row->device_name),(string)$row->family_id,$db);$db->transactionCommit();$this->respond(['data'=>$tokens]);}catch(\Throwable $error){$db->transactionRollback();$this->respond(['code'=>'refresh_failed','message'=>'Sign in again.'],401);}
    }
    public function logout(): never
    {
        $this->requireAuthenticated();$header=(string)$this->app->getInput()->server->get('HTTP_AUTHORIZATION','','string');if(preg_match('/^Bearer\s+(kba_\S+)$/i',trim($header),$m)){$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$db->setQuery($db->getQuery(true)->update($db->quoteName('#__kaar_api_sessions'))->set($db->quoteName('revoked_at').'='.$db->quote(Factory::getDate()->toSql()))->set($db->quoteName('revoke_reason').'='.$db->quote('logout'))->where($db->quoteName('access_hash').'='.$db->quote(hash('sha256',$m[1]))))->execute();}$this->respond(['data'=>['loggedOut'=>true]]);
    }
    private function issueSession(int $userId,string $deviceName,?string $familyId,$db): array
    {
        $params=ComponentHelper::getParams('com_kaarbooking');$accessMinutes=max(5,min(60,(int)$params->get('api_access_minutes',15)));$refreshDays=max(1,min(90,(int)$params->get('api_refresh_days',30)));$maxDevices=max(1,min(10,(int)$params->get('api_max_devices',5)));$now=Factory::getDate();$ids=$db->setQuery($db->getQuery(true)->select('id')->from($db->quoteName('#__kaar_api_sessions'))->where($db->quoteName('user_id').'='.$userId)->where($db->quoteName('revoked_at').' IS NULL')->where($db->quoteName('refresh_expires').'>='.$db->quote($now->toSql()))->order('created ASC'))->loadColumn()?:[];if(count($ids)>=$maxDevices){$revoke=array_slice(array_map('intval',$ids),0,count($ids)-$maxDevices+1);$db->setQuery($db->getQuery(true)->update($db->quoteName('#__kaar_api_sessions'))->set($db->quoteName('revoked_at').'='.$db->quote($now->toSql()))->set($db->quoteName('revoke_reason').'='.$db->quote('device_limit'))->where($db->quoteName('id').' IN ('.implode(',',$revoke).')'))->execute();}
        $access='kba_'.$this->b64(random_bytes(32));$refresh='kbr_'.$this->b64(random_bytes(48));$accessExpiry=(clone $now)->modify('+'.$accessMinutes.' minutes');$refreshExpiry=(clone $now)->modify('+'.$refreshDays.' days');$row=(object)['family_id'=>$familyId?:$this->uuid(),'user_id'=>$userId,'access_hash'=>hash('sha256',$access),'refresh_hash'=>hash('sha256',$refresh),'device_name'=>mb_substr($deviceName!==''?$deviceName:'Mobile app',0,120),'access_expires'=>$accessExpiry->toSql(),'refresh_expires'=>$refreshExpiry->toSql(),'last_used'=>$now->toSql(),'revoked_at'=>null,'revoke_reason'=>null,'created'=>$now->toSql()];$db->insertObject('#__kaar_api_sessions',$row,'id');return ['accessToken'=>$access,'refreshToken'=>$refresh,'tokenType'=>'Bearer','expiresIn'=>$accessMinutes*60,'accessExpiresAt'=>$accessExpiry->toISO8601(),'refreshExpiresAt'=>$refreshExpiry->toISO8601(),'sessionId'=>(int)$row->id];
    }
    private function b64(string $bytes): string{return rtrim(strtr(base64_encode($bytes),'+/','-_'),'=');}
    private function uuid(): string{$h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-'.dechex((hexdec($h[16])&3)|8).substr($h,17,3).'-'.substr($h,20,12);}
}
