<?php
namespace KaarBooking\Component\KaarBooking\Api\Controller;
defined('_JEXEC') or die;
final class RidesController extends BaseJsonController
{
    private function db(){return \Joomla\CMS\Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);}
    private function body():array{$data=json_decode(file_get_contents('php://input'),true,32,JSON_THROW_ON_ERROR);return is_array($data)?$data:[];}
    private function rideId():int{return $this->app->getInput()->getInt('id');}
    private function driver():object
    {
        $db=$this->db();$q=$db->getQuery(true)->select(['id','status','compliance_status','online_state'])->from($db->quoteName('#__kaar_drivers'))->where($db->quoteName('user_id').'='.(int)$this->app->getIdentity()->id);$driver=$db->setQuery($q,0,1)->loadObject();if(!$driver)$this->respond(['code'=>'driver_profile_required','message'=>'A driver profile is required.'],403);return $driver;
    }
    public function create():never
    {
        $this->requireAuthenticated();$body=$this->body();foreach(['pickupLat','pickupLng','dropLat','dropLng','origin','destination'] as $key){if(!isset($body[$key]))$this->respond(['code'=>'validation_error','message'=>'Missing '.$key],422);}$lat=(float)$body['pickupLat'];$lng=(float)$body['pickupLng'];$dlat=(float)$body['dropLat'];$dlng=(float)$body['dropLng'];if(abs($lat)>90||abs($dlat)>90||abs($lng)>180||abs($dlng)>180)$this->respond(['code'=>'validation_error','message'=>'Invalid coordinates'],422);
        $db=$this->db();$now=new \DateTimeImmutable('now',new \DateTimeZone('UTC'));$ref=\KaarBooking\Component\KaarBooking\Administrator\Domain\Booking\BookingReference::generate($now);$user=$this->app->getIdentity();$pin=(string)random_int(1000,9999);$db->transactionStart();try{$booking=(object)['reference'=>$ref,'source'=>'realtime_dispatch','product_type'=>'on_demand_ride','service_type'=>'online_driver','customer_id'=>null,'customer_name'=>$user->name,'customer_email'=>$user->email,'customer_phone'=>'','origin_text'=>mb_substr((string)$body['origin'],0,500),'destination_text'=>mb_substr((string)$body['destination'],0,500),'stops_json'=>'[]','departure_at'=>$now->format('Y-m-d H:i:s'),'return_at'=>null,'passengers'=>max(1,min(8,(int)($body['passengers']??1))),'driver_mode'=>'with_driver','status'=>'confirmed','payment_status'=>'unpaid','pricing_snapshot'=>null,'total_amount'=>0,'currency'=>'INR','created_by'=>(int)$user->id,'created'=>$now->format('Y-m-d H:i:s'),'modified_by'=>0,'version'=>1];$db->insertObject('#__kaar_bookings',$booking,'id');$ride=(object)['booking_id'=>(int)$booking->id,'driver_id'=>null,'vehicle_id'=>null,'dispatch_status'=>'requested','pickup_lat'=>$lat,'pickup_lng'=>$lng,'drop_lat'=>$dlat,'drop_lng'=>$dlng,'trip_pin_hash'=>password_hash($pin,PASSWORD_DEFAULT),'requested_at'=>$now->format('Y-m-d H:i:s'),'accepted_at'=>null,'arrived_at'=>null,'started_at'=>null,'completed_at'=>null];$db->insertObject('#__kaar_rides',$ride,'id');$db->transactionCommit();$this->respond(['data'=>['rideId'=>(int)$ride->id,'bookingReference'=>$ref,'status'=>'requested','tripPin'=>$pin]],201);}catch(\Throwable $error){$db->transactionRollback();$this->respond(['code'=>'ride_create_failed','message'=>'Ride request could not be created.'],500);}
    }
    public function display($cachable=false,$urlparams=[]):never
    {
        $this->requireAuthenticated();$db=$this->db();$id=$this->rideId();$userId=(int)$this->app->getIdentity()->id;$q=$db->getQuery(true)->select(['r.id','r.dispatch_status','r.driver_id','r.vehicle_id','r.requested_at','r.accepted_at','r.arrived_at','r.started_at','r.completed_at','b.reference','b.origin_text','b.destination_text','b.created_by'])->from($db->quoteName('#__kaar_rides','r'))->join('INNER',$db->quoteName('#__kaar_bookings','b').' ON '.$db->quoteName('b.id').'='.$db->quoteName('r.booking_id'))->where($db->quoteName('r.id').'='.$id);$row=$db->setQuery($q)->loadAssoc();if(!$row)$this->respond(['code'=>'not_found','message'=>'Ride not found'],404);$driver=$db->setQuery($db->getQuery(true)->select('id')->from($db->quoteName('#__kaar_drivers'))->where($db->quoteName('user_id').'='.$userId),0,1)->loadResult();if((int)$row['created_by']!==$userId&&(int)$row['driver_id']!==(int)$driver)$this->respond(['code'=>'forbidden','message'=>'Not allowed'],403);unset($row['created_by']);$this->respond(['data'=>$row]);
    }
    public function offers():never
    {
        $this->requireAuthenticated();$driver=$this->driver();if($driver->status!=='active'||$driver->compliance_status!=='verified'||$driver->online_state!=='online')$this->respond(['data'=>[]]);$db=$this->db();$q=$db->getQuery(true)->select(['r.id','r.pickup_lat','r.pickup_lng','r.drop_lat','r.drop_lng','r.requested_at','b.origin_text','b.destination_text','b.passengers'])->from($db->quoteName('#__kaar_rides','r'))->join('INNER',$db->quoteName('#__kaar_bookings','b').' ON '.$db->quoteName('b.id').'='.$db->quoteName('r.booking_id'))->where($db->quoteName('r.dispatch_status').'='.$db->quote('requested'))->where($db->quoteName('r.driver_id').' IS NULL')->order('r.requested_at ASC');$this->respond(['data'=>$db->setQuery($q,0,20)->loadAssocList()?:[]]);
    }
    public function accept():never
    {
        $this->requireAuthenticated();$driver=$this->driver();if($driver->status!=='active'||$driver->compliance_status!=='verified'||$driver->online_state!=='online')$this->respond(['code'=>'driver_not_eligible','message'=>'Driver is not eligible or online.'],409);$db=$this->db();$now=\Joomla\CMS\Factory::getDate()->toSql();$q=$db->getQuery(true)->update($db->quoteName('#__kaar_rides'))->set($db->quoteName('driver_id').'='.(int)$driver->id)->set($db->quoteName('dispatch_status').'='.$db->quote('accepted'))->set($db->quoteName('accepted_at').'='.$db->quote($now))->where($db->quoteName('id').'='.$this->rideId())->where($db->quoteName('dispatch_status').'='.$db->quote('requested'))->where($db->quoteName('driver_id').' IS NULL');$db->setQuery($q)->execute();if($db->getAffectedRows()!==1)$this->respond(['code'=>'offer_unavailable','message'=>'This ride was accepted or cancelled.'],409);$this->queueCustomerNotification('ride_confirmed');$this->respond(['data'=>['rideId'=>$this->rideId(),'status'=>'accepted']]);
    }
    public function arrive():never{$this->driverTransition('accepted','arrived','arrived_at');}
    public function complete():never{$this->driverTransition('in_progress','completed','completed_at');}
    public function start():never
    {
        $this->requireAuthenticated();$driver=$this->driver();$pin=(string)($this->body()['tripPin']??'');$db=$this->db();$q=$db->getQuery(true)->select('trip_pin_hash')->from($db->quoteName('#__kaar_rides'))->where($db->quoteName('id').'='.$this->rideId())->where($db->quoteName('driver_id').'='.(int)$driver->id)->where($db->quoteName('dispatch_status').'='.$db->quote('arrived'));$hash=(string)$db->setQuery($q)->loadResult();if($hash===''||!password_verify($pin,$hash))$this->respond(['code'=>'invalid_trip_pin','message'=>'Trip PIN is invalid.'],409);$this->driverTransition('arrived','in_progress','started_at',$driver);
    }
    private function driverTransition(string $from,string $to,string $timeColumn,?object $knownDriver=null):never
    {
        $this->requireAuthenticated();$driver=$knownDriver??$this->driver();$db=$this->db();$q=$db->getQuery(true)->update($db->quoteName('#__kaar_rides'))->set($db->quoteName('dispatch_status').'='.$db->quote($to))->set($db->quoteName($timeColumn).'='.$db->quote(\Joomla\CMS\Factory::getDate()->toSql()))->where($db->quoteName('id').'='.$this->rideId())->where($db->quoteName('driver_id').'='.(int)$driver->id)->where($db->quoteName('dispatch_status').'='.$db->quote($from));$db->setQuery($q)->execute();if($db->getAffectedRows()!==1)$this->respond(['code'=>'invalid_ride_state','message'=>'Ride state changed; refresh and try again.'],409);$this->queueCustomerNotification($to==='arrived'?'rider_arrived':'ride_'.$to);$this->respond(['data'=>['rideId'=>$this->rideId(),'status'=>$to]]);
    }
    public function availability():never
    {
        $this->requireAuthenticated();$driver=$this->driver();$state=(string)($this->body()['state']??'');if(!in_array($state,['online','offline'],true))$this->respond(['code'=>'validation_error','message'=>'State must be online or offline.'],422);if($state==='online'&&($driver->status!=='active'||$driver->compliance_status!=='verified'))$this->respond(['code'=>'driver_not_eligible','message'=>'Active, compliant drivers may go online.'],409);$db=$this->db();$db->setQuery($db->getQuery(true)->update($db->quoteName('#__kaar_drivers'))->set($db->quoteName('online_state').'='.$db->quote($state))->set($db->quoteName('modified').'='.$db->quote(\Joomla\CMS\Factory::getDate()->toSql()))->where($db->quoteName('id').'='.(int)$driver->id))->execute();$this->respond(['data'=>['state'=>$state]]);
    }
    public function cancel():never
    {
        $this->requireAuthenticated();$db=$this->db();$id=$this->rideId();$userId=(int)$this->app->getIdentity()->id;$driverId=(int)$db->setQuery($db->getQuery(true)->select('id')->from($db->quoteName('#__kaar_drivers'))->where($db->quoteName('user_id').'='.$userId),0,1)->loadResult();$q=$db->getQuery(true)->select(['r.driver_id','r.dispatch_status','b.created_by'])->from($db->quoteName('#__kaar_rides','r'))->join('INNER',$db->quoteName('#__kaar_bookings','b').' ON b.id=r.booking_id')->where('r.id='.$id);$ride=$db->setQuery($q,0,1)->loadObject();if(!$ride)$this->respond(['code'=>'not_found','message'=>'Ride not found.'],404);if((int)$ride->created_by!==$userId&&(int)$ride->driver_id!==$driverId)$this->respond(['code'=>'forbidden','message'=>'Not allowed.'],403);if(!in_array($ride->dispatch_status,['requested','accepted','arrived'],true))$this->respond(['code'=>'invalid_ride_state','message'=>'This ride can no longer be cancelled.'],409);$q=$db->getQuery(true)->update($db->quoteName('#__kaar_rides'))->set($db->quoteName('dispatch_status').'='.$db->quote('cancelled'))->where($db->quoteName('id').'='.$id)->where($db->quoteName('dispatch_status').'='.$db->quote($ride->dispatch_status));$db->setQuery($q)->execute();if($db->getAffectedRows()!==1)$this->respond(['code'=>'invalid_ride_state','message'=>'Ride state changed; refresh and try again.'],409);$this->queueCustomerNotification('ride_cancelled');$this->respond(['data'=>['rideId'=>$id,'status'=>'cancelled']]);
    }
    private function queueCustomerNotification(string $event):void
    {
        $db=$this->db();$q=$db->getQuery(true)->select('b.created_by')->from($db->quoteName('#__kaar_rides','r'))->join('INNER',$db->quoteName('#__kaar_bookings','b').' ON b.id=r.booking_id')->where('r.id='.$this->rideId());$userId=(int)$db->setQuery($q,0,1)->loadResult();if($userId<1)return;$now=\Joomla\CMS\Factory::getDate()->toSql();$row=(object)['user_id'=>$userId,'channel'=>'push','event_type'=>$event,'subject_type'=>'ride','subject_id'=>$this->rideId(),'payload_json'=>json_encode(['rideId'=>$this->rideId(),'event'=>$event],JSON_THROW_ON_ERROR),'status'=>'queued','attempts'=>0,'available_at'=>$now,'sent_at'=>null,'last_error'=>null,'created'=>$now];$db->insertObject('#__kaar_notifications',$row);
    }
    public function location():never
    {
        $this->requireAuthenticated();$driver=$this->driver();$body=$this->body();$lat=(float)($body['latitude']??999);$lng=(float)($body['longitude']??999);if(abs($lat)>90||abs($lng)>180)$this->respond(['code'=>'invalid_location','message'=>'Invalid location'],422);$rideId=isset($body['rideId'])?(int)$body['rideId']:null;if($rideId){$db=$this->db();$owned=(int)$db->setQuery($db->getQuery(true)->select('COUNT(*)')->from($db->quoteName('#__kaar_rides'))->where($db->quoteName('id').'='.$rideId)->where($db->quoteName('driver_id').'='.(int)$driver->id)->where($db->quoteName('dispatch_status').' IN ('.$db->quote('accepted').','.$db->quote('arrived').','.$db->quote('in_progress').')'))->loadResult();if($owned!==1)$this->respond(['code'=>'ride_not_active','message'=>'No active assigned ride'],409);}$row=(object)['driver_id'=>(int)$driver->id,'ride_id'=>$rideId,'latitude'=>$lat,'longitude'=>$lng,'accuracy_m'=>isset($body['accuracyM'])?max(0,(float)$body['accuracyM']):null,'recorded_at'=>\Joomla\CMS\Factory::getDate()->toSql()];$this->db()->insertObject('#__kaar_driver_locations',$row);$this->respond(['data'=>['recorded'=>true]]);
    }
    public function update():never{$this->respond(['code'=>'use_state_action','message'=>'Use an explicit ride state action.'],405);}
}
