<?php
namespace KaarBooking\Component\KaarBooking\Administrator\Controller;
defined('_JEXEC') or die;
use Joomla\CMS\Factory; use Joomla\CMS\MVC\Controller\BaseController; use Joomla\CMS\Router\Route; use Joomla\CMS\Session\Session; use KaarBooking\Component\KaarBooking\Administrator\Domain\Booking\BookingStatus; use KaarBooking\Component\KaarBooking\Administrator\Domain\Booking\BookingReference;
final class BookingController extends BaseController
{
    public function createPhone():void
    {
        Session::checkToken('post') or jexit('Invalid token');$user=$this->app->getIdentity();if(!$user->authorise('core.create','com_kaarbooking'))throw new \RuntimeException('Not authorised',403);$name=trim($this->input->post->getString('customer_name'));$phone=trim($this->input->post->getString('customer_phone'));$departureRaw=$this->input->post->getString('departure_at');$product=$this->input->post->getCmd('product_type');if($name===''||$phone===''||!in_array($product,['vehicle','package'],true))throw new \DomainException('Customer, phone and booking product are required.');try{$departure=new \DateTimeImmutable($departureRaw,new \DateTimeZone('UTC'));}catch(\Throwable){throw new \DomainException('Valid departure date and time are required.');}if($departure<=new \DateTimeImmutable('now',new \DateTimeZone('UTC')))throw new \DomainException('Departure must be in the future.');$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$now=new \DateTimeImmutable('now',new \DateTimeZone('UTC'));$row=(object)['reference'=>BookingReference::generate($now),'source'=>'phone','product_type'=>$product==='package'?'tour_package':'scheduled_vehicle','service_type'=>$this->input->post->getCmd('service_type',$product==='package'?'tour_package':'outstation'),'customer_id'=>null,'customer_name'=>mb_substr($name,0,190),'customer_email'=>mb_substr(trim($this->input->post->getString('customer_email')),0,190),'customer_phone'=>mb_substr($phone,0,40),'package_id'=>$product==='package'?($this->input->post->getInt('package_id')?:null):null,'departure_id'=>null,'vehicle_type_id'=>$product==='vehicle'?($this->input->post->getInt('vehicle_type_id')?:null):null,'origin_text'=>mb_substr(trim($this->input->post->getString('origin_text')),0,500),'destination_text'=>mb_substr(trim($this->input->post->getString('destination_text')),0,500),'stops_json'=>'[]','departure_at'=>$departure->format('Y-m-d H:i:s'),'return_at'=>null,'passengers'=>max(1,$this->input->post->getInt('passengers',1)),'driver_mode'=>$this->input->post->getCmd('driver_mode','with_driver'),'status'=>'pending_admin_review','payment_status'=>'unpaid','pricing_snapshot'=>null,'total_amount'=>max(0,$this->input->post->getFloat('total_amount')),'currency'=>'INR','admin_notes'=>trim($this->input->post->getString('admin_notes')),'created_by'=>(int)$user->id,'created'=>$now->format('Y-m-d H:i:s'),'modified_by'=>0,'modified'=>null,'version'=>1];$db->insertObject('#__kaar_bookings',$row,'id');$db->insertObject('#__kaar_booking_history',(object)['booking_id'=>$row->id,'from_status'=>null,'to_status'=>'pending_admin_review','actor_id'=>(int)$user->id,'reason'=>'Created from customer phone call','correlation_id'=>bin2hex(random_bytes(12)),'created'=>$now->format('Y-m-d H:i:s')]);$this->app->enqueueMessage('Phone booking '.$row->reference.' created for manual review.','success');$this->setRedirect(Route::_('index.php?option=com_kaarbooking&view=bookings',false));
    }
    public function transition(): void
    {
        Session::checkToken('post') or jexit('Invalid token');$user=$this->app->getIdentity();if(!$user->authorise('kaarbooking.booking.confirm','com_kaarbooking'))throw new \RuntimeException('Not authorised',403);
        $id=$this->input->post->getInt('id');$nextRaw=$this->input->post->getCmd('status');$reason=trim($this->input->post->getString('reason'));
        try{$next=BookingStatus::from($nextRaw);$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$q=$db->getQuery(true)->select(['status','version'])->from($db->quoteName('#__kaar_bookings'))->where($db->quoteName('id').'='.(int)$id);$currentRow=$db->setQuery($q)->loadAssoc();if(!$currentRow)throw new \DomainException('Booking not found');$current=BookingStatus::from($currentRow['status']);if(!$current->canTransitionTo($next,false))throw new \DomainException('Invalid scheduled booking transition');$now=Factory::getDate()->toSql();$update=$db->getQuery(true)->update($db->quoteName('#__kaar_bookings'))->set($db->quoteName('status').'='.$db->quote($next->value))->set($db->quoteName('modified').'='.$db->quote($now))->set($db->quoteName('modified_by').'='.(int)$user->id)->set($db->quoteName('version').'='.$db->quoteName('version').'+1')->where($db->quoteName('id').'='.(int)$id)->where($db->quoteName('version').'='.(int)$currentRow['version']);$db->setQuery($update)->execute();if($db->getAffectedRows()!==1)throw new \RuntimeException('Booking changed by another user; refresh and try again.');$history=(object)['booking_id'=>$id,'from_status'=>$current->value,'to_status'=>$next->value,'actor_id'=>(int)$user->id,'reason'=>$reason,'correlation_id'=>bin2hex(random_bytes(12)),'created'=>$now];$db->insertObject('#__kaar_booking_history',$history);$this->app->enqueueMessage('Booking updated.','success');}catch(\Throwable $error){$this->app->enqueueMessage($error->getMessage(),'error');}
        $this->setRedirect(Route::_('index.php?option=com_kaarbooking&view=bookings',false));
    }
}
