<?php
namespace KaarBooking\Component\KaarBooking\Administrator\Controller;
defined('_JEXEC') or die;
use Joomla\CMS\Factory;use Joomla\CMS\MVC\Controller\BaseController;use Joomla\CMS\Router\Route;use Joomla\CMS\Session\Session;use KaarBooking\Component\KaarBooking\Administrator\Service\MediaUploadService;
final class VehiclesController extends BaseController
{
 public function save():void{Session::checkToken('post')or jexit('Invalid token');$user=$this->app->getIdentity();if(!$user->authorise('core.create','com_kaarbooking'))throw new \RuntimeException('Not authorised',403);$registration=strtoupper(trim($this->input->post->getString('registration_number')));$typeId=$this->input->post->getInt('vehicle_type_id');if($registration===''||$typeId<1)throw new \DomainException('Registration and vehicle type are required.');$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$row=(object)['company_id'=>$this->input->post->getInt('company_id')?:null,'vehicle_type_id'=>$typeId,'registration_number'=>mb_substr($registration,0,64),'make'=>mb_substr(trim($this->input->post->getString('make')),0,100),'model'=>mb_substr(trim($this->input->post->getString('model')),0,100),'model_year'=>$this->input->post->getInt('model_year')?:null,'condition_status'=>$this->input->post->getCmd('condition_status','good'),'operational_status'=>'active','compliance_status'=>'pending','odometer_km'=>$this->input->post->getFloat('odometer_km')?:null,'state'=>1,'created'=>Factory::getDate()->toSql(),'modified'=>null];$db->insertObject('#__kaar_vehicles',$row,'id');MediaUploadService::store($this->input->files->get('vehicle_image',[],'array'),'vehicle',(int)$row->id,(int)$user->id,1,1,'profile');$this->app->enqueueMessage('Vehicle added. Add and verify its compliance documents before allocation.','success');$this->setRedirect(Route::_('index.php?option=com_kaarbooking&view=vehicles',false));}
 public function inspect():void{Session::checkToken('post')or jexit('Invalid token');$user=$this->app->getIdentity();if(!$user->authorise('kaarbooking.vehicle.inspect','com_kaarbooking'))throw new \RuntimeException('Not authorised',403);$vehicleId=$this->input->post->getInt('vehicle_id');$date=$this->input->post->getString('inspection_date');$result=$this->input->post->getCmd('result');$next=$this->input->post->getString('next_due_date');if($vehicleId<1||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||!in_array($result,['passed','conditional','failed'],true))throw new \DomainException('Valid vehicle, date and result are required.');$checks=['identity'=>$this->input->post->getInt('check_identity')===1,'roadworthy'=>$this->input->post->getInt('check_roadworthy')===1,'safety'=>$this->input->post->getInt('check_safety')===1,'cleanliness'=>$this->input->post->getInt('check_cleanliness')===1];$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$now=Factory::getDate()->toSql();$db->transactionStart();try{$row=(object)['vehicle_id'=>$vehicleId,'driver_id'=>$this->input->post->getInt('driver_id')?:null,'inspector_id'=>(int)$user->id,'inspection_date'=>$date,'result'=>$result,'odometer_km'=>$this->input->post->getFloat('odometer_km')?:null,'checklist_json'=>json_encode($checks,JSON_THROW_ON_ERROR),'notes'=>trim($this->input->post->getString('notes')),'next_due_date'=>preg_match('/^\d{4}-\d{2}-\d{2}$/',$next)?$next:null,'created'=>$now,'modified'=>null];$db->insertObject('#__kaar_vehicle_inspections',$row,'id');$status=$result==='passed'?'verified':($result==='failed'?'blocked':'conditional');$db->setQuery($db->getQuery(true)->update($db->quoteName('#__kaar_vehicles'))->set($db->quoteName('compliance_status').'='.$db->quote($status))->set($db->quoteName('operational_status').'='.$db->quote($result==='failed'?'blocked':'active'))->set($db->quoteName('modified').'='.$db->quote($now))->where($db->quoteName('id').'='.$vehicleId))->execute();$db->transactionCommit();$this->app->enqueueMessage('Vehicle inspection recorded.','success');}catch(\Throwable $e){$db->transactionRollback();throw $e;}$this->setRedirect(Route::_('index.php?option=com_kaarbooking&view=inspections',false));}
}


