<?php
namespace KaarBooking\Component\KaarBooking\Administrator\View\Drivers;defined('_JEXEC') or die;use Joomla\CMS\Factory;use Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;
final class HtmlView extends BaseHtmlView{public array $items=[],$companies=[],$users=[],$stats=[],$filters=[];public function display($tpl=null):void{if(!Factory::getApplication()->getIdentity()->authorise('core.manage','com_kaarbooking'))throw new \RuntimeException('Not authorised',403);$app=Factory::getApplication();$db=Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);$this->filters=['search'=>trim((string)$app->input->getString('filter_search','')),'company'=>$app->input->getInt('filter_company'),'status'=>$app->input->getCmd('filter_status'),'online'=>$app->input->getCmd('filter_online')];$q=$db->getQuery(true)->select(['d.*','u.email','c.name AS company_name','m.path AS image_path'])->from('#__kaar_drivers d')->join('LEFT','#__users u ON u.id=d.user_id')->join('LEFT','#__kaar_companies c ON c.id=d.company_id')->join('LEFT',"#__kaar_media m ON m.subject_type='driver' AND m.subject_id=d.id AND m.purpose='profile'");if($this->filters['search']!=='')$q->where('(d.display_name LIKE '.$db->quote('%'.$this->filters['search'].'%').' OR u.email LIKE '.$db->quote('%'.$this->filters['search'].'%').')');if($this->filters['company'])$q->where('d.company_id='.(int)$this->filters['company']);if($this->filters['status']!=='')$q->where('d.compliance_status='.$db->quote($this->filters['status']));if($this->filters['online']!=='')$q->where('d.online_state='.$db->quote($this->filters['online']));$q->order('d.display_name');$this->items=$db->setQuery($q,0,500)->loadAssocList()?:[];$this->companies=$db->setQuery("SELECT id,name FROM #__kaar_companies WHERE status='active' ORDER BY name")->loadAssocList()?:[];$this->users=$db->setQuery('SELECT id,name,email FROM #__users WHERE block=0 ORDER BY name',0,500)->loadAssocList()?:[];$this->stats=['total'=>(int)$db->setQuery('SELECT COUNT(*) FROM #__kaar_drivers')->loadResult(),'active'=>(int)$db->setQuery("SELECT COUNT(*) FROM #__kaar_drivers WHERE status='active'")->loadResult(),'compliant'=>(int)$db->setQuery("SELECT COUNT(*) FROM #__kaar_drivers WHERE compliance_status='verified'")->loadResult(),'online'=>(int)$db->setQuery("SELECT COUNT(*) FROM #__kaar_drivers WHERE online_state='online'")->loadResult()];parent::display($tpl);}}






